package button

//type AutoGenerated struct {
//	Button []struct {
//		Name      string `json:"name"`
//		SubButton []struct {
//			Type      string `json:"type"`
//			Name      string `json:"name"`
//			Key       string `json:"key"`
//			SubButton []struct {
//				Type      string        `json:"type"`
//				Name      string        `json:"name"`
//				Key       string        `json:"key"`
//				SubButton []interface{} `json:"sub_button"`
//			} `json:"sub_button"`
//		} `json:"sub_button,omitempty"`
//		Type    string `json:"type,omitempty"`
//		Key     string `json:"key,omitempty"`
//		MediaID string `json:"media_id,omitempty"`
//	} `json:"button"`
//}
//Button 微信菜单按钮的子集
type Button struct {
	Type      string    `json:"type"`
	Name      string    `json:"name"`
	Key       string    `json:"key"`
	SubButton []*Button `json:"sub_button"`
}

//WXButton 微信菜单按钮
type WXButton struct {
	Button *Button `json:"button"`
}
